Add deferred named version
kentcdodds/import-all.macro pull request #10
Opened 2018-10-23 14:52 UTC by sanohin

**What**:

**Why**:

**How**:

**Checklist**:

* [ ] Documentation
* [ ] Tests
* [ ] Ready to be merged 
* [ ] Added myself to contributors table

2018-10-23 15:04 UTC, kentcdodds reviewed
Thanks, but I'm going to need a little convincing that this is a good idea. My first impression is that this is stepping a little beyond the bounds of how I want import-all.macro to work...

2018-10-23 19:54 UTC, sanohin commented
Well, It would be difficult to convince you probably. While working in few different companies I saw the approach of exposing 'kinda' library additional components or functions to globals and using them somewhere dynamically (component/fn name cannot be statically determined). 

So I think this can be a great drop-in replacement for such use cases with no changes to the architecture of the whole app.

2018-10-24 19:16 UTC, sanohin commented on src/macro.js
> +  const getAst = code => {
btw, not sure how to get covered this function by tests

2018-10-24 21:27 UTC, kentcdodds requested changes
Sorry, I think I'm going to close this one. You can make your own macro for your projects.

Thanks anyway!

2018-10-24 21:28 UTC, closed without merging